name: Trigger News Endpoint

on:
  schedule:
    - cron: '0 10 * * *' # Every day at 10:00 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger News API
        run: |
          curl -X GET ${{secrets.VERCEL_URL}}/news/trigger/get?token=${{ secrets.ACTIONS_TOKEN }} 