# Script to run a news routine job using GitHub Actions
name: News Routine Trigger

on:
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10:00 AM UTC
  workflow_dispatch:

jobs:
  run-news-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run news script
        run: node services\getNewsRoutine.js